### ISSUE TITLE
Error when uploading in xiao esp32s3

### ISSUE THREAD

**Issue by giannisj5** [wollewald/MPU9250_WE#18]
c:\Users\user\Arduino\libraries\MPU9250_WE\src/MPU6500_WE.h:337:28: error: section attribute not allowed for 'accOffsetVal'
  337 |     RTC_DATA_ATTR xyzFloat accOffsetVal; // to be able to keep offsets after deep sleep
      |                            ^~~~~~~~~~~~
c:\Users\user\Arduino\libraries\MPU9250_WE\src/MPU6500_WE.h:338:28: error: section attribute not allowed for 'gyrOffsetVal'
  338 |     RTC_DATA_ATTR xyzFloat gyrOffsetVal;
      |                            ^~~~~~~~~~~~

**Comment by wollewald** [comment]
@giannisj5 Something I tried found its way into the the release 1.2.8. Now it should work again (1.2.9).

**Comment by giannisj5** [comment]
thank you very much, very fast fix. Everything is working perfect
