### ISSUE TITLE
Is this library support multiple MPU6500 using SPI?

### ISSUE THREAD

**Issue by dayinji** [wollewald/MPU9250_WE#9]
First of all thanks to the author.

I would like to know is this lib support  multiple MPU6500 using SPI? 
I have an ESP32 board and more than 6 MPU6500 sensors. I try to connect them together and transfer datas by SPI. 
However, it seems that only one sensor connected successfully each time, while other sensor show 'not response' and they return wrong datas.

**Comment by wollewald** [comment]
Hi @dayinji , yes this is possible, but each MPU6500 needs a separate CS line.

For three MPU6500 modules it would look like this (please take appropriate pins - this shall only show the principle!):
````
const int csPin_1 = 10; 
const int csPin_2 = 11;
const int csPin_3 = 13;
bool useSPI = true;    // SPI use flag

MPU6500_WE myMPU6500_1 = MPU6500_WE(&SPI, csPin_1, useSPI);
MPU6500_WE myMPU6500_2 = MPU6500_WE(&SPI, csPin_2, useSPI);
MPU6500_WE myMPU6500_3 = MPU6500_WE(&SPI, csPin_3, useSPI);
````
I have not tried it but in theory this should work.

**Comment by dayinji** [comment]
Thank you for your very fast reply.
I try to write as your codes. However just one sensor print "connect successfully " and other sensor return "no response". I try to debug and found that MPU6500 expect a WHO_I_AM value to be 112 when inited, while those sensors not working return 96 (not 112)

`
      uint8_t MPU6500_WE::whoAmI(){
          return readMPU9250Register8(REGISTER_WHO_AM_I);
      }
`

**Comment by dayinji** [comment]
Thanks ! It works.
